# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

pkglib_IMAGES += g2ldr.mbr g2hdr.bin grldr.img

all: g2ldr.mbr g2hdr.bin

DISTCLEANFILES += g2ldr.mbr g2hdr.bin

g2hdr_bin_SOURCES = $(GRUB_CONTRIB)/ntldr-img/g2hdr.S

clean-image-g2hdr.bin.1:
	rm -f g2hdr.bin g2hdr.exec g2hdr_bin-__GRUB_CONTRIB__ntldr_img_g2hdr.o

CLEAN_IMAGE_TARGETS += clean-image-g2hdr.bin.1

mostlyclean-image-g2hdr.bin.1:
	rm -f g2hdr_bin-__GRUB_CONTRIB__ntldr_img_g2hdr.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-g2hdr.bin.1

ifneq ($(TARGET_APPLE_CC),1)
g2hdr.bin: g2hdr.exec
	$(OBJCOPY) -O $(g2hdr_bin_FORMAT) --strip-unneeded -R .note -R .comment -R .note.gnu.build-id -R .reginfo -R .rel.dyn $< $@
else
ifneq (g2hdr.exec,kernel.exec)
g2hdr.bin: g2hdr.exec ./grub-macho2img
	./grub-macho2img $< $@
else
g2hdr.bin: g2hdr.exec ./grub-macho2img
	./grub-macho2img --bss $< $@
endif
endif

g2hdr.exec: g2hdr_bin-__GRUB_CONTRIB__ntldr_img_g2hdr.o
	$(TARGET_CC) -o $@ $^ $(TARGET_LDFLAGS) $(g2hdr_bin_LDFLAGS)

g2hdr_bin-__GRUB_CONTRIB__ntldr_img_g2hdr.o: $(GRUB_CONTRIB)/ntldr-img/g2hdr.S $($(GRUB_CONTRIB)/ntldr-img/g2hdr.S_DEPENDENCIES)
	$(TARGET_CC) -I$(GRUB_CONTRIB)/ntldr-img -I$(srcdir)/$(GRUB_CONTRIB)/ntldr-img $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(g2hdr_bin_ASFLAGS) -MD -c -o $@ $<
-include g2hdr_bin-__GRUB_CONTRIB__ntldr_img_g2hdr.d

g2hdr_bin_ASFLAGS = $(COMMON_ASFLAGS)
g2hdr_bin_LDFLAGS = $(COMMON_LDFLAGS) $(TARGET_IMG_LDFLAGS)0x0
g2hdr_bin_FORMAT = binary

grldr_img_SOURCES = $(GRUB_CONTRIB)/ntldr-img/grldrstart.S $(GRUB_CONTRIB)/ntldr-img/ntfsbs.S

clean-image-grldr.img.1:
	rm -f grldr.img grldr.exec grldr_img-__GRUB_CONTRIB__ntldr_img_grldrstart.o grldr_img-__GRUB_CONTRIB__ntldr_img_ntfsbs.o

CLEAN_IMAGE_TARGETS += clean-image-grldr.img.1

mostlyclean-image-grldr.img.1:
	rm -f grldr_img-__GRUB_CONTRIB__ntldr_img_grldrstart.d grldr_img-__GRUB_CONTRIB__ntldr_img_ntfsbs.d

MOSTLYCLEAN_IMAGE_TARGETS += mostlyclean-image-grldr.img.1

ifneq ($(TARGET_APPLE_CC),1)
grldr.img: grldr.exec
	$(OBJCOPY) -O $(grldr_img_FORMAT) --strip-unneeded -R .note -R .comment -R .note.gnu.build-id -R .reginfo -R .rel.dyn $< $@
else
ifneq (grldr.exec,kernel.exec)
grldr.img: grldr.exec ./grub-macho2img
	./grub-macho2img $< $@
else
grldr.img: grldr.exec ./grub-macho2img
	./grub-macho2img --bss $< $@
endif
endif

grldr.exec: grldr_img-__GRUB_CONTRIB__ntldr_img_grldrstart.o grldr_img-__GRUB_CONTRIB__ntldr_img_ntfsbs.o
	$(TARGET_CC) -o $@ $^ $(TARGET_LDFLAGS) $(grldr_img_LDFLAGS)

grldr_img-__GRUB_CONTRIB__ntldr_img_grldrstart.o: $(GRUB_CONTRIB)/ntldr-img/grldrstart.S $($(GRUB_CONTRIB)/ntldr-img/grldrstart.S_DEPENDENCIES)
	$(TARGET_CC) -I$(GRUB_CONTRIB)/ntldr-img -I$(srcdir)/$(GRUB_CONTRIB)/ntldr-img $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(grldr_img_ASFLAGS) -MD -c -o $@ $<
-include grldr_img-__GRUB_CONTRIB__ntldr_img_grldrstart.d

grldr_img-__GRUB_CONTRIB__ntldr_img_ntfsbs.o: $(GRUB_CONTRIB)/ntldr-img/ntfsbs.S $($(GRUB_CONTRIB)/ntldr-img/ntfsbs.S_DEPENDENCIES)
	$(TARGET_CC) -I$(GRUB_CONTRIB)/ntldr-img -I$(srcdir)/$(GRUB_CONTRIB)/ntldr-img $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(grldr_img_ASFLAGS) -MD -c -o $@ $<
-include grldr_img-__GRUB_CONTRIB__ntldr_img_ntfsbs.d

grldr_img_ASFLAGS = $(COMMON_ASFLAGS) -DGRLDR_MBR
grldr_img_LDFLAGS = $(COMMON_LDFLAGS) $(TARGET_IMG_LDFLAGS)0x7c00
grldr_img_FORMAT = binary

grldr.mbr: grldr.img
	head -c 8192 $< > $@
DISTCLEANFILES += grldr.mbr

bin2h: $(GRUB_CONTRIB)/ntldr-img/bin2h.c
	$(CC) $^ -o $@
DISTCLEANFILES += bin2h

grub_mbr.h: grldr.mbr bin2h
	./bin2h grub_mbr 8192 < $< > $@
DISTCLEANFILES += grub_mbr.h

grubinst: $(GRUB_CONTRIB)/ntldr-img/grubinst.c $(GRUB_CONTRIB)/ntldr-img/utils.c grub_mbr.h
	$(CC) -I. -I$(GRUB_CONTRIB)/ntldr-img -DLINUX -o $@ $(GRUB_CONTRIB)/ntldr-img/grubinst.c $(GRUB_CONTRIB)/ntldr-img/utils.c
DISTCLEANFILES += grubinst

g2ldr.mbr: grubinst
	./grubinst --grub2 -o $@
DISTCLEANFILES += g2ldr.mbr
