# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

pkglib_MODULES += cpuid.mod
cpuid_mod_SOURCES = commands/i386/cpuid.c

clean-module-cpuid.mod.1:
	rm -f cpuid.mod mod-cpuid.o mod-cpuid.c pre-cpuid.o cpuid_mod-commands_i386_cpuid.o und-cpuid.lst

CLEAN_MODULE_TARGETS += clean-module-cpuid.mod.1

clean-module-cpuid.mod-symbol.1:
	rm -f def-cpuid.lst

CLEAN_MODULE_TARGETS += clean-module-cpuid.mod-symbol.1
DEFSYMFILES += def-cpuid.lst
mostlyclean-module-cpuid.mod.1:
	rm -f cpuid_mod-commands_i386_cpuid.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-cpuid.mod.1
UNDSYMFILES += und-cpuid.lst

ifneq ($(TARGET_APPLE_CC),1)
cpuid.mod: pre-cpuid.o mod-cpuid.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(cpuid_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-cpuid.o mod-cpuid.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
cpuid.mod: pre-cpuid.o mod-cpuid.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(cpuid_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-cpuid.o mod-cpuid.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-cpuid.o: $(cpuid_mod_DEPENDENCIES) cpuid_mod-commands_i386_cpuid.o
	-rm -f $@
	$(TARGET_CC) $(cpuid_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ cpuid_mod-commands_i386_cpuid.o

mod-cpuid.o: mod-cpuid.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -c -o $@ $<

mod-cpuid.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'cpuid' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-cpuid.lst: pre-cpuid.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 cpuid/' > $@
else
def-cpuid.lst: pre-cpuid.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 cpuid/' > $@
endif

und-cpuid.lst: pre-cpuid.o
	echo 'cpuid' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

cpuid_mod-commands_i386_cpuid.o: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES)
	$(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -MD -c -o $@ $<
-include cpuid_mod-commands_i386_cpuid.d

clean-module-cpuid_mod-commands_i386_cpuid-extra.1:
	rm -f cmd-cpuid_mod-commands_i386_cpuid.lst fs-cpuid_mod-commands_i386_cpuid.lst partmap-cpuid_mod-commands_i386_cpuid.lst handler-cpuid_mod-commands_i386_cpuid.lst parttool-cpuid_mod-commands_i386_cpuid.lst video-cpuid_mod-commands_i386_cpuid.lst terminal-cpuid_mod-commands_i386_cpuid.lst

CLEAN_MODULE_TARGETS += clean-module-cpuid_mod-commands_i386_cpuid-extra.1

COMMANDFILES += cmd-cpuid_mod-commands_i386_cpuid.lst
FSFILES += fs-cpuid_mod-commands_i386_cpuid.lst
PARTTOOLFILES += parttool-cpuid_mod-commands_i386_cpuid.lst
PARTMAPFILES += partmap-cpuid_mod-commands_i386_cpuid.lst
HANDLERFILES += handler-cpuid_mod-commands_i386_cpuid.lst
TERMINALFILES += terminal-cpuid_mod-commands_i386_cpuid.lst
VIDEOFILES += video-cpuid_mod-commands_i386_cpuid.lst

cmd-cpuid_mod-commands_i386_cpuid.lst: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh cpuid > $@ || (rm -f $@; exit 1)

fs-cpuid_mod-commands_i386_cpuid.lst: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh cpuid > $@ || (rm -f $@; exit 1)

parttool-cpuid_mod-commands_i386_cpuid.lst: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh cpuid > $@ || (rm -f $@; exit 1)

partmap-cpuid_mod-commands_i386_cpuid.lst: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh cpuid > $@ || (rm -f $@; exit 1)

handler-cpuid_mod-commands_i386_cpuid.lst: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh cpuid > $@ || (rm -f $@; exit 1)

terminal-cpuid_mod-commands_i386_cpuid.lst: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh cpuid > $@ || (rm -f $@; exit 1)

video-cpuid_mod-commands_i386_cpuid.lst: commands/i386/cpuid.c $(commands/i386/cpuid.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Icommands/i386 -I$(srcdir)/commands/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(cpuid_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh cpuid > $@ || (rm -f $@; exit 1)

cpuid_mod_CFLAGS = $(COMMON_CFLAGS)
cpuid_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += at_keyboard.mod
at_keyboard_mod_SOURCES = term/at_keyboard.c

clean-module-at_keyboard.mod.1:
	rm -f at_keyboard.mod mod-at_keyboard.o mod-at_keyboard.c pre-at_keyboard.o at_keyboard_mod-term_at_keyboard.o und-at_keyboard.lst

CLEAN_MODULE_TARGETS += clean-module-at_keyboard.mod.1

clean-module-at_keyboard.mod-symbol.1:
	rm -f def-at_keyboard.lst

CLEAN_MODULE_TARGETS += clean-module-at_keyboard.mod-symbol.1
DEFSYMFILES += def-at_keyboard.lst
mostlyclean-module-at_keyboard.mod.1:
	rm -f at_keyboard_mod-term_at_keyboard.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-at_keyboard.mod.1
UNDSYMFILES += und-at_keyboard.lst

ifneq ($(TARGET_APPLE_CC),1)
at_keyboard.mod: pre-at_keyboard.o mod-at_keyboard.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(at_keyboard_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-at_keyboard.o mod-at_keyboard.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
at_keyboard.mod: pre-at_keyboard.o mod-at_keyboard.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(at_keyboard_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-at_keyboard.o mod-at_keyboard.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-at_keyboard.o: $(at_keyboard_mod_DEPENDENCIES) at_keyboard_mod-term_at_keyboard.o
	-rm -f $@
	$(TARGET_CC) $(at_keyboard_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ at_keyboard_mod-term_at_keyboard.o

mod-at_keyboard.o: mod-at_keyboard.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -c -o $@ $<

mod-at_keyboard.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'at_keyboard' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-at_keyboard.lst: pre-at_keyboard.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 at_keyboard/' > $@
else
def-at_keyboard.lst: pre-at_keyboard.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 at_keyboard/' > $@
endif

und-at_keyboard.lst: pre-at_keyboard.o
	echo 'at_keyboard' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

at_keyboard_mod-term_at_keyboard.o: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES)
	$(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -MD -c -o $@ $<
-include at_keyboard_mod-term_at_keyboard.d

clean-module-at_keyboard_mod-term_at_keyboard-extra.1:
	rm -f cmd-at_keyboard_mod-term_at_keyboard.lst fs-at_keyboard_mod-term_at_keyboard.lst partmap-at_keyboard_mod-term_at_keyboard.lst handler-at_keyboard_mod-term_at_keyboard.lst parttool-at_keyboard_mod-term_at_keyboard.lst video-at_keyboard_mod-term_at_keyboard.lst terminal-at_keyboard_mod-term_at_keyboard.lst

CLEAN_MODULE_TARGETS += clean-module-at_keyboard_mod-term_at_keyboard-extra.1

COMMANDFILES += cmd-at_keyboard_mod-term_at_keyboard.lst
FSFILES += fs-at_keyboard_mod-term_at_keyboard.lst
PARTTOOLFILES += parttool-at_keyboard_mod-term_at_keyboard.lst
PARTMAPFILES += partmap-at_keyboard_mod-term_at_keyboard.lst
HANDLERFILES += handler-at_keyboard_mod-term_at_keyboard.lst
TERMINALFILES += terminal-at_keyboard_mod-term_at_keyboard.lst
VIDEOFILES += video-at_keyboard_mod-term_at_keyboard.lst

cmd-at_keyboard_mod-term_at_keyboard.lst: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh at_keyboard > $@ || (rm -f $@; exit 1)

fs-at_keyboard_mod-term_at_keyboard.lst: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh at_keyboard > $@ || (rm -f $@; exit 1)

parttool-at_keyboard_mod-term_at_keyboard.lst: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh at_keyboard > $@ || (rm -f $@; exit 1)

partmap-at_keyboard_mod-term_at_keyboard.lst: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh at_keyboard > $@ || (rm -f $@; exit 1)

handler-at_keyboard_mod-term_at_keyboard.lst: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh at_keyboard > $@ || (rm -f $@; exit 1)

terminal-at_keyboard_mod-term_at_keyboard.lst: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh at_keyboard > $@ || (rm -f $@; exit 1)

video-at_keyboard_mod-term_at_keyboard.lst: term/at_keyboard.c $(term/at_keyboard.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iterm -I$(srcdir)/term $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(at_keyboard_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh at_keyboard > $@ || (rm -f $@; exit 1)

at_keyboard_mod_CFLAGS = $(COMMON_CFLAGS)
at_keyboard_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += vga_text.mod
vga_text_mod_SOURCES = term/i386/pc/vga_text.c term/i386/vga_common.c

clean-module-vga_text.mod.1:
	rm -f vga_text.mod mod-vga_text.o mod-vga_text.c pre-vga_text.o vga_text_mod-term_i386_pc_vga_text.o vga_text_mod-term_i386_vga_common.o und-vga_text.lst

CLEAN_MODULE_TARGETS += clean-module-vga_text.mod.1

clean-module-vga_text.mod-symbol.1:
	rm -f def-vga_text.lst

CLEAN_MODULE_TARGETS += clean-module-vga_text.mod-symbol.1
DEFSYMFILES += def-vga_text.lst
mostlyclean-module-vga_text.mod.1:
	rm -f vga_text_mod-term_i386_pc_vga_text.d vga_text_mod-term_i386_vga_common.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-vga_text.mod.1
UNDSYMFILES += und-vga_text.lst

ifneq ($(TARGET_APPLE_CC),1)
vga_text.mod: pre-vga_text.o mod-vga_text.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(vga_text_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-vga_text.o mod-vga_text.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
vga_text.mod: pre-vga_text.o mod-vga_text.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(vga_text_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-vga_text.o mod-vga_text.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-vga_text.o: $(vga_text_mod_DEPENDENCIES) vga_text_mod-term_i386_pc_vga_text.o vga_text_mod-term_i386_vga_common.o
	-rm -f $@
	$(TARGET_CC) $(vga_text_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ vga_text_mod-term_i386_pc_vga_text.o vga_text_mod-term_i386_vga_common.o

mod-vga_text.o: mod-vga_text.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -c -o $@ $<

mod-vga_text.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'vga_text' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-vga_text.lst: pre-vga_text.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 vga_text/' > $@
else
def-vga_text.lst: pre-vga_text.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 vga_text/' > $@
endif

und-vga_text.lst: pre-vga_text.o
	echo 'vga_text' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

vga_text_mod-term_i386_pc_vga_text.o: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES)
	$(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -MD -c -o $@ $<
-include vga_text_mod-term_i386_pc_vga_text.d

clean-module-vga_text_mod-term_i386_pc_vga_text-extra.1:
	rm -f cmd-vga_text_mod-term_i386_pc_vga_text.lst fs-vga_text_mod-term_i386_pc_vga_text.lst partmap-vga_text_mod-term_i386_pc_vga_text.lst handler-vga_text_mod-term_i386_pc_vga_text.lst parttool-vga_text_mod-term_i386_pc_vga_text.lst video-vga_text_mod-term_i386_pc_vga_text.lst terminal-vga_text_mod-term_i386_pc_vga_text.lst

CLEAN_MODULE_TARGETS += clean-module-vga_text_mod-term_i386_pc_vga_text-extra.1

COMMANDFILES += cmd-vga_text_mod-term_i386_pc_vga_text.lst
FSFILES += fs-vga_text_mod-term_i386_pc_vga_text.lst
PARTTOOLFILES += parttool-vga_text_mod-term_i386_pc_vga_text.lst
PARTMAPFILES += partmap-vga_text_mod-term_i386_pc_vga_text.lst
HANDLERFILES += handler-vga_text_mod-term_i386_pc_vga_text.lst
TERMINALFILES += terminal-vga_text_mod-term_i386_pc_vga_text.lst
VIDEOFILES += video-vga_text_mod-term_i386_pc_vga_text.lst

cmd-vga_text_mod-term_i386_pc_vga_text.lst: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh vga_text > $@ || (rm -f $@; exit 1)

fs-vga_text_mod-term_i386_pc_vga_text.lst: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh vga_text > $@ || (rm -f $@; exit 1)

parttool-vga_text_mod-term_i386_pc_vga_text.lst: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh vga_text > $@ || (rm -f $@; exit 1)

partmap-vga_text_mod-term_i386_pc_vga_text.lst: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh vga_text > $@ || (rm -f $@; exit 1)

handler-vga_text_mod-term_i386_pc_vga_text.lst: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh vga_text > $@ || (rm -f $@; exit 1)

terminal-vga_text_mod-term_i386_pc_vga_text.lst: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh vga_text > $@ || (rm -f $@; exit 1)

video-vga_text_mod-term_i386_pc_vga_text.lst: term/i386/pc/vga_text.c $(term/i386/pc/vga_text.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386/pc -I$(srcdir)/term/i386/pc $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh vga_text > $@ || (rm -f $@; exit 1)

vga_text_mod-term_i386_vga_common.o: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES)
	$(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -MD -c -o $@ $<
-include vga_text_mod-term_i386_vga_common.d

clean-module-vga_text_mod-term_i386_vga_common-extra.1:
	rm -f cmd-vga_text_mod-term_i386_vga_common.lst fs-vga_text_mod-term_i386_vga_common.lst partmap-vga_text_mod-term_i386_vga_common.lst handler-vga_text_mod-term_i386_vga_common.lst parttool-vga_text_mod-term_i386_vga_common.lst video-vga_text_mod-term_i386_vga_common.lst terminal-vga_text_mod-term_i386_vga_common.lst

CLEAN_MODULE_TARGETS += clean-module-vga_text_mod-term_i386_vga_common-extra.1

COMMANDFILES += cmd-vga_text_mod-term_i386_vga_common.lst
FSFILES += fs-vga_text_mod-term_i386_vga_common.lst
PARTTOOLFILES += parttool-vga_text_mod-term_i386_vga_common.lst
PARTMAPFILES += partmap-vga_text_mod-term_i386_vga_common.lst
HANDLERFILES += handler-vga_text_mod-term_i386_vga_common.lst
TERMINALFILES += terminal-vga_text_mod-term_i386_vga_common.lst
VIDEOFILES += video-vga_text_mod-term_i386_vga_common.lst

cmd-vga_text_mod-term_i386_vga_common.lst: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh vga_text > $@ || (rm -f $@; exit 1)

fs-vga_text_mod-term_i386_vga_common.lst: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh vga_text > $@ || (rm -f $@; exit 1)

parttool-vga_text_mod-term_i386_vga_common.lst: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh vga_text > $@ || (rm -f $@; exit 1)

partmap-vga_text_mod-term_i386_vga_common.lst: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh vga_text > $@ || (rm -f $@; exit 1)

handler-vga_text_mod-term_i386_vga_common.lst: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh vga_text > $@ || (rm -f $@; exit 1)

terminal-vga_text_mod-term_i386_vga_common.lst: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh vga_text > $@ || (rm -f $@; exit 1)

video-vga_text_mod-term_i386_vga_common.lst: term/i386/vga_common.c $(term/i386/vga_common.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iterm/i386 -I$(srcdir)/term/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(vga_text_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh vga_text > $@ || (rm -f $@; exit 1)

vga_text_mod_CFLAGS = $(COMMON_CFLAGS)
vga_text_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += relocator.mod
relocator_mod_SOURCES = lib/i386/relocator.c lib/i386/relocator_asm.S lib/i386/relocator_backward.S

clean-module-relocator.mod.1:
	rm -f relocator.mod mod-relocator.o mod-relocator.c pre-relocator.o relocator_mod-lib_i386_relocator.o relocator_mod-lib_i386_relocator_asm.o relocator_mod-lib_i386_relocator_backward.o und-relocator.lst

CLEAN_MODULE_TARGETS += clean-module-relocator.mod.1

clean-module-relocator.mod-symbol.1:
	rm -f def-relocator.lst

CLEAN_MODULE_TARGETS += clean-module-relocator.mod-symbol.1
DEFSYMFILES += def-relocator.lst
mostlyclean-module-relocator.mod.1:
	rm -f relocator_mod-lib_i386_relocator.d relocator_mod-lib_i386_relocator_asm.d relocator_mod-lib_i386_relocator_backward.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-relocator.mod.1
UNDSYMFILES += und-relocator.lst

ifneq ($(TARGET_APPLE_CC),1)
relocator.mod: pre-relocator.o mod-relocator.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(relocator_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-relocator.o mod-relocator.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
relocator.mod: pre-relocator.o mod-relocator.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(relocator_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-relocator.o mod-relocator.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-relocator.o: $(relocator_mod_DEPENDENCIES) relocator_mod-lib_i386_relocator.o relocator_mod-lib_i386_relocator_asm.o relocator_mod-lib_i386_relocator_backward.o
	-rm -f $@
	$(TARGET_CC) $(relocator_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ relocator_mod-lib_i386_relocator.o relocator_mod-lib_i386_relocator_asm.o relocator_mod-lib_i386_relocator_backward.o

mod-relocator.o: mod-relocator.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -c -o $@ $<

mod-relocator.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'relocator' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-relocator.lst: pre-relocator.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 relocator/' > $@
else
def-relocator.lst: pre-relocator.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 relocator/' > $@
endif

und-relocator.lst: pre-relocator.o
	echo 'relocator' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

relocator_mod-lib_i386_relocator.o: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES)
	$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -MD -c -o $@ $<
-include relocator_mod-lib_i386_relocator.d

clean-module-relocator_mod-lib_i386_relocator-extra.1:
	rm -f cmd-relocator_mod-lib_i386_relocator.lst fs-relocator_mod-lib_i386_relocator.lst partmap-relocator_mod-lib_i386_relocator.lst handler-relocator_mod-lib_i386_relocator.lst parttool-relocator_mod-lib_i386_relocator.lst video-relocator_mod-lib_i386_relocator.lst terminal-relocator_mod-lib_i386_relocator.lst

CLEAN_MODULE_TARGETS += clean-module-relocator_mod-lib_i386_relocator-extra.1

COMMANDFILES += cmd-relocator_mod-lib_i386_relocator.lst
FSFILES += fs-relocator_mod-lib_i386_relocator.lst
PARTTOOLFILES += parttool-relocator_mod-lib_i386_relocator.lst
PARTMAPFILES += partmap-relocator_mod-lib_i386_relocator.lst
HANDLERFILES += handler-relocator_mod-lib_i386_relocator.lst
TERMINALFILES += terminal-relocator_mod-lib_i386_relocator.lst
VIDEOFILES += video-relocator_mod-lib_i386_relocator.lst

cmd-relocator_mod-lib_i386_relocator.lst: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh relocator > $@ || (rm -f $@; exit 1)

fs-relocator_mod-lib_i386_relocator.lst: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh relocator > $@ || (rm -f $@; exit 1)

parttool-relocator_mod-lib_i386_relocator.lst: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh relocator > $@ || (rm -f $@; exit 1)

partmap-relocator_mod-lib_i386_relocator.lst: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh relocator > $@ || (rm -f $@; exit 1)

handler-relocator_mod-lib_i386_relocator.lst: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh relocator > $@ || (rm -f $@; exit 1)

terminal-relocator_mod-lib_i386_relocator.lst: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh relocator > $@ || (rm -f $@; exit 1)

video-relocator_mod-lib_i386_relocator.lst: lib/i386/relocator.c $(lib/i386/relocator.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(relocator_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh relocator > $@ || (rm -f $@; exit 1)

relocator_mod-lib_i386_relocator_asm.o: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES)
	$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -MD -c -o $@ $<
-include relocator_mod-lib_i386_relocator_asm.d

clean-module-relocator_mod-lib_i386_relocator_asm-extra.1:
	rm -f cmd-relocator_mod-lib_i386_relocator_asm.lst fs-relocator_mod-lib_i386_relocator_asm.lst partmap-relocator_mod-lib_i386_relocator_asm.lst handler-relocator_mod-lib_i386_relocator_asm.lst parttool-relocator_mod-lib_i386_relocator_asm.lst video-relocator_mod-lib_i386_relocator_asm.lst terminal-relocator_mod-lib_i386_relocator_asm.lst

CLEAN_MODULE_TARGETS += clean-module-relocator_mod-lib_i386_relocator_asm-extra.1

COMMANDFILES += cmd-relocator_mod-lib_i386_relocator_asm.lst
FSFILES += fs-relocator_mod-lib_i386_relocator_asm.lst
PARTTOOLFILES += parttool-relocator_mod-lib_i386_relocator_asm.lst
PARTMAPFILES += partmap-relocator_mod-lib_i386_relocator_asm.lst
HANDLERFILES += handler-relocator_mod-lib_i386_relocator_asm.lst
TERMINALFILES += terminal-relocator_mod-lib_i386_relocator_asm.lst
VIDEOFILES += video-relocator_mod-lib_i386_relocator_asm.lst

cmd-relocator_mod-lib_i386_relocator_asm.lst: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh relocator > $@ || (rm -f $@; exit 1)

fs-relocator_mod-lib_i386_relocator_asm.lst: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh relocator > $@ || (rm -f $@; exit 1)

parttool-relocator_mod-lib_i386_relocator_asm.lst: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh relocator > $@ || (rm -f $@; exit 1)

partmap-relocator_mod-lib_i386_relocator_asm.lst: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh relocator > $@ || (rm -f $@; exit 1)

handler-relocator_mod-lib_i386_relocator_asm.lst: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh relocator > $@ || (rm -f $@; exit 1)

terminal-relocator_mod-lib_i386_relocator_asm.lst: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh relocator > $@ || (rm -f $@; exit 1)

video-relocator_mod-lib_i386_relocator_asm.lst: lib/i386/relocator_asm.S $(lib/i386/relocator_asm.S_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh relocator > $@ || (rm -f $@; exit 1)

relocator_mod-lib_i386_relocator_backward.o: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES)
	$(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -MD -c -o $@ $<
-include relocator_mod-lib_i386_relocator_backward.d

clean-module-relocator_mod-lib_i386_relocator_backward-extra.1:
	rm -f cmd-relocator_mod-lib_i386_relocator_backward.lst fs-relocator_mod-lib_i386_relocator_backward.lst partmap-relocator_mod-lib_i386_relocator_backward.lst handler-relocator_mod-lib_i386_relocator_backward.lst parttool-relocator_mod-lib_i386_relocator_backward.lst video-relocator_mod-lib_i386_relocator_backward.lst terminal-relocator_mod-lib_i386_relocator_backward.lst

CLEAN_MODULE_TARGETS += clean-module-relocator_mod-lib_i386_relocator_backward-extra.1

COMMANDFILES += cmd-relocator_mod-lib_i386_relocator_backward.lst
FSFILES += fs-relocator_mod-lib_i386_relocator_backward.lst
PARTTOOLFILES += parttool-relocator_mod-lib_i386_relocator_backward.lst
PARTMAPFILES += partmap-relocator_mod-lib_i386_relocator_backward.lst
HANDLERFILES += handler-relocator_mod-lib_i386_relocator_backward.lst
TERMINALFILES += terminal-relocator_mod-lib_i386_relocator_backward.lst
VIDEOFILES += video-relocator_mod-lib_i386_relocator_backward.lst

cmd-relocator_mod-lib_i386_relocator_backward.lst: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh relocator > $@ || (rm -f $@; exit 1)

fs-relocator_mod-lib_i386_relocator_backward.lst: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh relocator > $@ || (rm -f $@; exit 1)

parttool-relocator_mod-lib_i386_relocator_backward.lst: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh relocator > $@ || (rm -f $@; exit 1)

partmap-relocator_mod-lib_i386_relocator_backward.lst: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh relocator > $@ || (rm -f $@; exit 1)

handler-relocator_mod-lib_i386_relocator_backward.lst: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh relocator > $@ || (rm -f $@; exit 1)

terminal-relocator_mod-lib_i386_relocator_backward.lst: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh relocator > $@ || (rm -f $@; exit 1)

video-relocator_mod-lib_i386_relocator_backward.lst: lib/i386/relocator_backward.S $(lib/i386/relocator_backward.S_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Ilib/i386 -I$(srcdir)/lib/i386 $(TARGET_CPPFLAGS) -DASM_FILE=1 $(TARGET_ASFLAGS) $(relocator_mod_ASFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh relocator > $@ || (rm -f $@; exit 1)

relocator_mod_CFLAGS = $(COMMON_CFLAGS)
relocator_mod_ASFLAGS = $(COMMON_ASFLAGS)
relocator_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += ata.mod
ata_mod_SOURCES = disk/ata.c

clean-module-ata.mod.1:
	rm -f ata.mod mod-ata.o mod-ata.c pre-ata.o ata_mod-disk_ata.o und-ata.lst

CLEAN_MODULE_TARGETS += clean-module-ata.mod.1

clean-module-ata.mod-symbol.1:
	rm -f def-ata.lst

CLEAN_MODULE_TARGETS += clean-module-ata.mod-symbol.1
DEFSYMFILES += def-ata.lst
mostlyclean-module-ata.mod.1:
	rm -f ata_mod-disk_ata.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-ata.mod.1
UNDSYMFILES += und-ata.lst

ifneq ($(TARGET_APPLE_CC),1)
ata.mod: pre-ata.o mod-ata.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(ata_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-ata.o mod-ata.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
ata.mod: pre-ata.o mod-ata.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(ata_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-ata.o mod-ata.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-ata.o: $(ata_mod_DEPENDENCIES) ata_mod-disk_ata.o
	-rm -f $@
	$(TARGET_CC) $(ata_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ ata_mod-disk_ata.o

mod-ata.o: mod-ata.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -c -o $@ $<

mod-ata.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'ata' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-ata.lst: pre-ata.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 ata/' > $@
else
def-ata.lst: pre-ata.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 ata/' > $@
endif

und-ata.lst: pre-ata.o
	echo 'ata' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

ata_mod-disk_ata.o: disk/ata.c $(disk/ata.c_DEPENDENCIES)
	$(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -MD -c -o $@ $<
-include ata_mod-disk_ata.d

clean-module-ata_mod-disk_ata-extra.1:
	rm -f cmd-ata_mod-disk_ata.lst fs-ata_mod-disk_ata.lst partmap-ata_mod-disk_ata.lst handler-ata_mod-disk_ata.lst parttool-ata_mod-disk_ata.lst video-ata_mod-disk_ata.lst terminal-ata_mod-disk_ata.lst

CLEAN_MODULE_TARGETS += clean-module-ata_mod-disk_ata-extra.1

COMMANDFILES += cmd-ata_mod-disk_ata.lst
FSFILES += fs-ata_mod-disk_ata.lst
PARTTOOLFILES += parttool-ata_mod-disk_ata.lst
PARTMAPFILES += partmap-ata_mod-disk_ata.lst
HANDLERFILES += handler-ata_mod-disk_ata.lst
TERMINALFILES += terminal-ata_mod-disk_ata.lst
VIDEOFILES += video-ata_mod-disk_ata.lst

cmd-ata_mod-disk_ata.lst: disk/ata.c $(disk/ata.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh ata > $@ || (rm -f $@; exit 1)

fs-ata_mod-disk_ata.lst: disk/ata.c $(disk/ata.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh ata > $@ || (rm -f $@; exit 1)

parttool-ata_mod-disk_ata.lst: disk/ata.c $(disk/ata.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh ata > $@ || (rm -f $@; exit 1)

partmap-ata_mod-disk_ata.lst: disk/ata.c $(disk/ata.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh ata > $@ || (rm -f $@; exit 1)

handler-ata_mod-disk_ata.lst: disk/ata.c $(disk/ata.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh ata > $@ || (rm -f $@; exit 1)

terminal-ata_mod-disk_ata.lst: disk/ata.c $(disk/ata.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh ata > $@ || (rm -f $@; exit 1)

video-ata_mod-disk_ata.lst: disk/ata.c $(disk/ata.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Idisk -I$(srcdir)/disk $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(ata_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh ata > $@ || (rm -f $@; exit 1)

ata_mod_CFLAGS = $(COMMON_CFLAGS)
ata_mod_LDFLAGS = $(COMMON_LDFLAGS)

# For setpci.mod
pkglib_MODULES += setpci.mod
setpci_mod_SOURCES = commands/setpci.c

clean-module-setpci.mod.1:
	rm -f setpci.mod mod-setpci.o mod-setpci.c pre-setpci.o setpci_mod-commands_setpci.o und-setpci.lst

CLEAN_MODULE_TARGETS += clean-module-setpci.mod.1

clean-module-setpci.mod-symbol.1:
	rm -f def-setpci.lst

CLEAN_MODULE_TARGETS += clean-module-setpci.mod-symbol.1
DEFSYMFILES += def-setpci.lst
mostlyclean-module-setpci.mod.1:
	rm -f setpci_mod-commands_setpci.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-setpci.mod.1
UNDSYMFILES += und-setpci.lst

ifneq ($(TARGET_APPLE_CC),1)
setpci.mod: pre-setpci.o mod-setpci.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(setpci_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-setpci.o mod-setpci.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
setpci.mod: pre-setpci.o mod-setpci.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(setpci_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-setpci.o mod-setpci.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-setpci.o: $(setpci_mod_DEPENDENCIES) setpci_mod-commands_setpci.o
	-rm -f $@
	$(TARGET_CC) $(setpci_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ setpci_mod-commands_setpci.o

mod-setpci.o: mod-setpci.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -c -o $@ $<

mod-setpci.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'setpci' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-setpci.lst: pre-setpci.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 setpci/' > $@
else
def-setpci.lst: pre-setpci.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 setpci/' > $@
endif

und-setpci.lst: pre-setpci.o
	echo 'setpci' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

setpci_mod-commands_setpci.o: commands/setpci.c $(commands/setpci.c_DEPENDENCIES)
	$(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -MD -c -o $@ $<
-include setpci_mod-commands_setpci.d

clean-module-setpci_mod-commands_setpci-extra.1:
	rm -f cmd-setpci_mod-commands_setpci.lst fs-setpci_mod-commands_setpci.lst partmap-setpci_mod-commands_setpci.lst handler-setpci_mod-commands_setpci.lst parttool-setpci_mod-commands_setpci.lst video-setpci_mod-commands_setpci.lst terminal-setpci_mod-commands_setpci.lst

CLEAN_MODULE_TARGETS += clean-module-setpci_mod-commands_setpci-extra.1

COMMANDFILES += cmd-setpci_mod-commands_setpci.lst
FSFILES += fs-setpci_mod-commands_setpci.lst
PARTTOOLFILES += parttool-setpci_mod-commands_setpci.lst
PARTMAPFILES += partmap-setpci_mod-commands_setpci.lst
HANDLERFILES += handler-setpci_mod-commands_setpci.lst
TERMINALFILES += terminal-setpci_mod-commands_setpci.lst
VIDEOFILES += video-setpci_mod-commands_setpci.lst

cmd-setpci_mod-commands_setpci.lst: commands/setpci.c $(commands/setpci.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh setpci > $@ || (rm -f $@; exit 1)

fs-setpci_mod-commands_setpci.lst: commands/setpci.c $(commands/setpci.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh setpci > $@ || (rm -f $@; exit 1)

parttool-setpci_mod-commands_setpci.lst: commands/setpci.c $(commands/setpci.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh setpci > $@ || (rm -f $@; exit 1)

partmap-setpci_mod-commands_setpci.lst: commands/setpci.c $(commands/setpci.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh setpci > $@ || (rm -f $@; exit 1)

handler-setpci_mod-commands_setpci.lst: commands/setpci.c $(commands/setpci.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh setpci > $@ || (rm -f $@; exit 1)

terminal-setpci_mod-commands_setpci.lst: commands/setpci.c $(commands/setpci.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh setpci > $@ || (rm -f $@; exit 1)

video-setpci_mod-commands_setpci.lst: commands/setpci.c $(commands/setpci.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Icommands -I$(srcdir)/commands $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(setpci_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh setpci > $@ || (rm -f $@; exit 1)

setpci_mod_CFLAGS = $(COMMON_CFLAGS)
setpci_mod_LDFLAGS = $(COMMON_LDFLAGS)

pkglib_MODULES += multiboot.mod
multiboot_mod_SOURCES = loader/i386/multiboot.c \
			loader/i386/multiboot_mbi.c \
                        loader/multiboot_loader.c

clean-module-multiboot.mod.1:
	rm -f multiboot.mod mod-multiboot.o mod-multiboot.c pre-multiboot.o multiboot_mod-loader_i386_multiboot.o multiboot_mod-loader_i386_multiboot_mbi.o multiboot_mod-loader_multiboot_loader.o und-multiboot.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot.mod.1

clean-module-multiboot.mod-symbol.1:
	rm -f def-multiboot.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot.mod-symbol.1
DEFSYMFILES += def-multiboot.lst
mostlyclean-module-multiboot.mod.1:
	rm -f multiboot_mod-loader_i386_multiboot.d multiboot_mod-loader_i386_multiboot_mbi.d multiboot_mod-loader_multiboot_loader.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-multiboot.mod.1
UNDSYMFILES += und-multiboot.lst

ifneq ($(TARGET_APPLE_CC),1)
multiboot.mod: pre-multiboot.o mod-multiboot.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(multiboot_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-multiboot.o mod-multiboot.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
multiboot.mod: pre-multiboot.o mod-multiboot.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(multiboot_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-multiboot.o mod-multiboot.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-multiboot.o: $(multiboot_mod_DEPENDENCIES) multiboot_mod-loader_i386_multiboot.o multiboot_mod-loader_i386_multiboot_mbi.o multiboot_mod-loader_multiboot_loader.o
	-rm -f $@
	$(TARGET_CC) $(multiboot_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ multiboot_mod-loader_i386_multiboot.o multiboot_mod-loader_i386_multiboot_mbi.o multiboot_mod-loader_multiboot_loader.o

mod-multiboot.o: mod-multiboot.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -c -o $@ $<

mod-multiboot.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'multiboot' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-multiboot.lst: pre-multiboot.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 multiboot/' > $@
else
def-multiboot.lst: pre-multiboot.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 multiboot/' > $@
endif

und-multiboot.lst: pre-multiboot.o
	echo 'multiboot' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

multiboot_mod-loader_i386_multiboot.o: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES)
	$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -MD -c -o $@ $<
-include multiboot_mod-loader_i386_multiboot.d

clean-module-multiboot_mod-loader_i386_multiboot-extra.1:
	rm -f cmd-multiboot_mod-loader_i386_multiboot.lst fs-multiboot_mod-loader_i386_multiboot.lst partmap-multiboot_mod-loader_i386_multiboot.lst handler-multiboot_mod-loader_i386_multiboot.lst parttool-multiboot_mod-loader_i386_multiboot.lst video-multiboot_mod-loader_i386_multiboot.lst terminal-multiboot_mod-loader_i386_multiboot.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot_mod-loader_i386_multiboot-extra.1

COMMANDFILES += cmd-multiboot_mod-loader_i386_multiboot.lst
FSFILES += fs-multiboot_mod-loader_i386_multiboot.lst
PARTTOOLFILES += parttool-multiboot_mod-loader_i386_multiboot.lst
PARTMAPFILES += partmap-multiboot_mod-loader_i386_multiboot.lst
HANDLERFILES += handler-multiboot_mod-loader_i386_multiboot.lst
TERMINALFILES += terminal-multiboot_mod-loader_i386_multiboot.lst
VIDEOFILES += video-multiboot_mod-loader_i386_multiboot.lst

cmd-multiboot_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh multiboot > $@ || (rm -f $@; exit 1)

fs-multiboot_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh multiboot > $@ || (rm -f $@; exit 1)

parttool-multiboot_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh multiboot > $@ || (rm -f $@; exit 1)

partmap-multiboot_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh multiboot > $@ || (rm -f $@; exit 1)

handler-multiboot_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh multiboot > $@ || (rm -f $@; exit 1)

terminal-multiboot_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh multiboot > $@ || (rm -f $@; exit 1)

video-multiboot_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh multiboot > $@ || (rm -f $@; exit 1)

multiboot_mod-loader_i386_multiboot_mbi.o: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES)
	$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -MD -c -o $@ $<
-include multiboot_mod-loader_i386_multiboot_mbi.d

clean-module-multiboot_mod-loader_i386_multiboot_mbi-extra.1:
	rm -f cmd-multiboot_mod-loader_i386_multiboot_mbi.lst fs-multiboot_mod-loader_i386_multiboot_mbi.lst partmap-multiboot_mod-loader_i386_multiboot_mbi.lst handler-multiboot_mod-loader_i386_multiboot_mbi.lst parttool-multiboot_mod-loader_i386_multiboot_mbi.lst video-multiboot_mod-loader_i386_multiboot_mbi.lst terminal-multiboot_mod-loader_i386_multiboot_mbi.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot_mod-loader_i386_multiboot_mbi-extra.1

COMMANDFILES += cmd-multiboot_mod-loader_i386_multiboot_mbi.lst
FSFILES += fs-multiboot_mod-loader_i386_multiboot_mbi.lst
PARTTOOLFILES += parttool-multiboot_mod-loader_i386_multiboot_mbi.lst
PARTMAPFILES += partmap-multiboot_mod-loader_i386_multiboot_mbi.lst
HANDLERFILES += handler-multiboot_mod-loader_i386_multiboot_mbi.lst
TERMINALFILES += terminal-multiboot_mod-loader_i386_multiboot_mbi.lst
VIDEOFILES += video-multiboot_mod-loader_i386_multiboot_mbi.lst

cmd-multiboot_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh multiboot > $@ || (rm -f $@; exit 1)

fs-multiboot_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh multiboot > $@ || (rm -f $@; exit 1)

parttool-multiboot_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh multiboot > $@ || (rm -f $@; exit 1)

partmap-multiboot_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh multiboot > $@ || (rm -f $@; exit 1)

handler-multiboot_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh multiboot > $@ || (rm -f $@; exit 1)

terminal-multiboot_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh multiboot > $@ || (rm -f $@; exit 1)

video-multiboot_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh multiboot > $@ || (rm -f $@; exit 1)

multiboot_mod-loader_multiboot_loader.o: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES)
	$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -MD -c -o $@ $<
-include multiboot_mod-loader_multiboot_loader.d

clean-module-multiboot_mod-loader_multiboot_loader-extra.1:
	rm -f cmd-multiboot_mod-loader_multiboot_loader.lst fs-multiboot_mod-loader_multiboot_loader.lst partmap-multiboot_mod-loader_multiboot_loader.lst handler-multiboot_mod-loader_multiboot_loader.lst parttool-multiboot_mod-loader_multiboot_loader.lst video-multiboot_mod-loader_multiboot_loader.lst terminal-multiboot_mod-loader_multiboot_loader.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot_mod-loader_multiboot_loader-extra.1

COMMANDFILES += cmd-multiboot_mod-loader_multiboot_loader.lst
FSFILES += fs-multiboot_mod-loader_multiboot_loader.lst
PARTTOOLFILES += parttool-multiboot_mod-loader_multiboot_loader.lst
PARTMAPFILES += partmap-multiboot_mod-loader_multiboot_loader.lst
HANDLERFILES += handler-multiboot_mod-loader_multiboot_loader.lst
TERMINALFILES += terminal-multiboot_mod-loader_multiboot_loader.lst
VIDEOFILES += video-multiboot_mod-loader_multiboot_loader.lst

cmd-multiboot_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh multiboot > $@ || (rm -f $@; exit 1)

fs-multiboot_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh multiboot > $@ || (rm -f $@; exit 1)

parttool-multiboot_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh multiboot > $@ || (rm -f $@; exit 1)

partmap-multiboot_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh multiboot > $@ || (rm -f $@; exit 1)

handler-multiboot_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh multiboot > $@ || (rm -f $@; exit 1)

terminal-multiboot_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh multiboot > $@ || (rm -f $@; exit 1)

video-multiboot_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh multiboot > $@ || (rm -f $@; exit 1)

multiboot_mod_CFLAGS = $(COMMON_CFLAGS)
multiboot_mod_LDFLAGS = $(COMMON_LDFLAGS)
multiboot_mod_ASFLAGS = $(COMMON_ASFLAGS)

pkglib_MODULES += multiboot2.mod
multiboot2_mod_SOURCES = loader/i386/multiboot.c \
			 loader/i386/multiboot_mbi.c \
                         loader/multiboot_loader.c

clean-module-multiboot2.mod.1:
	rm -f multiboot2.mod mod-multiboot2.o mod-multiboot2.c pre-multiboot2.o multiboot2_mod-loader_i386_multiboot.o multiboot2_mod-loader_i386_multiboot_mbi.o multiboot2_mod-loader_multiboot_loader.o und-multiboot2.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot2.mod.1

clean-module-multiboot2.mod-symbol.1:
	rm -f def-multiboot2.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot2.mod-symbol.1
DEFSYMFILES += def-multiboot2.lst
mostlyclean-module-multiboot2.mod.1:
	rm -f multiboot2_mod-loader_i386_multiboot.d multiboot2_mod-loader_i386_multiboot_mbi.d multiboot2_mod-loader_multiboot_loader.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-multiboot2.mod.1
UNDSYMFILES += und-multiboot2.lst

ifneq ($(TARGET_APPLE_CC),1)
multiboot2.mod: pre-multiboot2.o mod-multiboot2.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(multiboot2_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-multiboot2.o mod-multiboot2.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
multiboot2.mod: pre-multiboot2.o mod-multiboot2.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(multiboot2_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-multiboot2.o mod-multiboot2.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-multiboot2.o: $(multiboot2_mod_DEPENDENCIES) multiboot2_mod-loader_i386_multiboot.o multiboot2_mod-loader_i386_multiboot_mbi.o multiboot2_mod-loader_multiboot_loader.o
	-rm -f $@
	$(TARGET_CC) $(multiboot2_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ multiboot2_mod-loader_i386_multiboot.o multiboot2_mod-loader_i386_multiboot_mbi.o multiboot2_mod-loader_multiboot_loader.o

mod-multiboot2.o: mod-multiboot2.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -c -o $@ $<

mod-multiboot2.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'multiboot2' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-multiboot2.lst: pre-multiboot2.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 multiboot2/' > $@
else
def-multiboot2.lst: pre-multiboot2.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 multiboot2/' > $@
endif

und-multiboot2.lst: pre-multiboot2.o
	echo 'multiboot2' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

multiboot2_mod-loader_i386_multiboot.o: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES)
	$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -MD -c -o $@ $<
-include multiboot2_mod-loader_i386_multiboot.d

clean-module-multiboot2_mod-loader_i386_multiboot-extra.1:
	rm -f cmd-multiboot2_mod-loader_i386_multiboot.lst fs-multiboot2_mod-loader_i386_multiboot.lst partmap-multiboot2_mod-loader_i386_multiboot.lst handler-multiboot2_mod-loader_i386_multiboot.lst parttool-multiboot2_mod-loader_i386_multiboot.lst video-multiboot2_mod-loader_i386_multiboot.lst terminal-multiboot2_mod-loader_i386_multiboot.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot2_mod-loader_i386_multiboot-extra.1

COMMANDFILES += cmd-multiboot2_mod-loader_i386_multiboot.lst
FSFILES += fs-multiboot2_mod-loader_i386_multiboot.lst
PARTTOOLFILES += parttool-multiboot2_mod-loader_i386_multiboot.lst
PARTMAPFILES += partmap-multiboot2_mod-loader_i386_multiboot.lst
HANDLERFILES += handler-multiboot2_mod-loader_i386_multiboot.lst
TERMINALFILES += terminal-multiboot2_mod-loader_i386_multiboot.lst
VIDEOFILES += video-multiboot2_mod-loader_i386_multiboot.lst

cmd-multiboot2_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh multiboot2 > $@ || (rm -f $@; exit 1)

fs-multiboot2_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh multiboot2 > $@ || (rm -f $@; exit 1)

parttool-multiboot2_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh multiboot2 > $@ || (rm -f $@; exit 1)

partmap-multiboot2_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh multiboot2 > $@ || (rm -f $@; exit 1)

handler-multiboot2_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh multiboot2 > $@ || (rm -f $@; exit 1)

terminal-multiboot2_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh multiboot2 > $@ || (rm -f $@; exit 1)

video-multiboot2_mod-loader_i386_multiboot.lst: loader/i386/multiboot.c $(loader/i386/multiboot.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh multiboot2 > $@ || (rm -f $@; exit 1)

multiboot2_mod-loader_i386_multiboot_mbi.o: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES)
	$(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -MD -c -o $@ $<
-include multiboot2_mod-loader_i386_multiboot_mbi.d

clean-module-multiboot2_mod-loader_i386_multiboot_mbi-extra.1:
	rm -f cmd-multiboot2_mod-loader_i386_multiboot_mbi.lst fs-multiboot2_mod-loader_i386_multiboot_mbi.lst partmap-multiboot2_mod-loader_i386_multiboot_mbi.lst handler-multiboot2_mod-loader_i386_multiboot_mbi.lst parttool-multiboot2_mod-loader_i386_multiboot_mbi.lst video-multiboot2_mod-loader_i386_multiboot_mbi.lst terminal-multiboot2_mod-loader_i386_multiboot_mbi.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot2_mod-loader_i386_multiboot_mbi-extra.1

COMMANDFILES += cmd-multiboot2_mod-loader_i386_multiboot_mbi.lst
FSFILES += fs-multiboot2_mod-loader_i386_multiboot_mbi.lst
PARTTOOLFILES += parttool-multiboot2_mod-loader_i386_multiboot_mbi.lst
PARTMAPFILES += partmap-multiboot2_mod-loader_i386_multiboot_mbi.lst
HANDLERFILES += handler-multiboot2_mod-loader_i386_multiboot_mbi.lst
TERMINALFILES += terminal-multiboot2_mod-loader_i386_multiboot_mbi.lst
VIDEOFILES += video-multiboot2_mod-loader_i386_multiboot_mbi.lst

cmd-multiboot2_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh multiboot2 > $@ || (rm -f $@; exit 1)

fs-multiboot2_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh multiboot2 > $@ || (rm -f $@; exit 1)

parttool-multiboot2_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh multiboot2 > $@ || (rm -f $@; exit 1)

partmap-multiboot2_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh multiboot2 > $@ || (rm -f $@; exit 1)

handler-multiboot2_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh multiboot2 > $@ || (rm -f $@; exit 1)

terminal-multiboot2_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh multiboot2 > $@ || (rm -f $@; exit 1)

video-multiboot2_mod-loader_i386_multiboot_mbi.lst: loader/i386/multiboot_mbi.c $(loader/i386/multiboot_mbi.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iloader/i386 -I$(srcdir)/loader/i386 $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh multiboot2 > $@ || (rm -f $@; exit 1)

multiboot2_mod-loader_multiboot_loader.o: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES)
	$(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -MD -c -o $@ $<
-include multiboot2_mod-loader_multiboot_loader.d

clean-module-multiboot2_mod-loader_multiboot_loader-extra.1:
	rm -f cmd-multiboot2_mod-loader_multiboot_loader.lst fs-multiboot2_mod-loader_multiboot_loader.lst partmap-multiboot2_mod-loader_multiboot_loader.lst handler-multiboot2_mod-loader_multiboot_loader.lst parttool-multiboot2_mod-loader_multiboot_loader.lst video-multiboot2_mod-loader_multiboot_loader.lst terminal-multiboot2_mod-loader_multiboot_loader.lst

CLEAN_MODULE_TARGETS += clean-module-multiboot2_mod-loader_multiboot_loader-extra.1

COMMANDFILES += cmd-multiboot2_mod-loader_multiboot_loader.lst
FSFILES += fs-multiboot2_mod-loader_multiboot_loader.lst
PARTTOOLFILES += parttool-multiboot2_mod-loader_multiboot_loader.lst
PARTMAPFILES += partmap-multiboot2_mod-loader_multiboot_loader.lst
HANDLERFILES += handler-multiboot2_mod-loader_multiboot_loader.lst
TERMINALFILES += terminal-multiboot2_mod-loader_multiboot_loader.lst
VIDEOFILES += video-multiboot2_mod-loader_multiboot_loader.lst

cmd-multiboot2_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh multiboot2 > $@ || (rm -f $@; exit 1)

fs-multiboot2_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh multiboot2 > $@ || (rm -f $@; exit 1)

parttool-multiboot2_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh multiboot2 > $@ || (rm -f $@; exit 1)

partmap-multiboot2_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh multiboot2 > $@ || (rm -f $@; exit 1)

handler-multiboot2_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh multiboot2 > $@ || (rm -f $@; exit 1)

terminal-multiboot2_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh multiboot2 > $@ || (rm -f $@; exit 1)

video-multiboot2_mod-loader_multiboot_loader.lst: loader/multiboot_loader.c $(loader/multiboot_loader.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Iloader -I$(srcdir)/loader $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(multiboot2_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh multiboot2 > $@ || (rm -f $@; exit 1)

multiboot2_mod_CFLAGS = $(COMMON_CFLAGS) -DGRUB_USE_MULTIBOOT2
multiboot2_mod_LDFLAGS = $(COMMON_LDFLAGS)
multiboot2_mod_ASFLAGS = $(COMMON_ASFLAGS)
