# -*- makefile -*-
# Generated by genmk.rb, please don't edit!

# For grub-shell
grub-shell: tests/util/grub-shell.in config.status
	./config.status --file=$@:$<
	chmod +x $@
check_SCRIPTS += grub-shell
CLEANFILES += grub-shell

# For grub-shell-tester
grub-shell-tester: tests/util/grub-shell-tester.in config.status
	./config.status --file=$@:$<
	chmod +x $@
check_SCRIPTS += grub-shell-tester
CLEANFILES += grub-shell-tester

pkglib_MODULES += functional_test.mod
functional_test_mod_SOURCES = tests/lib/functional_test.c tests/lib/test.c

clean-module-functional_test.mod.1:
	rm -f functional_test.mod mod-functional_test.o mod-functional_test.c pre-functional_test.o functional_test_mod-tests_lib_functional_test.o functional_test_mod-tests_lib_test.o und-functional_test.lst

CLEAN_MODULE_TARGETS += clean-module-functional_test.mod.1

clean-module-functional_test.mod-symbol.1:
	rm -f def-functional_test.lst

CLEAN_MODULE_TARGETS += clean-module-functional_test.mod-symbol.1
DEFSYMFILES += def-functional_test.lst
mostlyclean-module-functional_test.mod.1:
	rm -f functional_test_mod-tests_lib_functional_test.d functional_test_mod-tests_lib_test.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-functional_test.mod.1
UNDSYMFILES += und-functional_test.lst

ifneq ($(TARGET_APPLE_CC),1)
functional_test.mod: pre-functional_test.o mod-functional_test.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(functional_test_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-functional_test.o mod-functional_test.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
functional_test.mod: pre-functional_test.o mod-functional_test.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(functional_test_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-functional_test.o mod-functional_test.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-functional_test.o: $(functional_test_mod_DEPENDENCIES) functional_test_mod-tests_lib_functional_test.o functional_test_mod-tests_lib_test.o
	-rm -f $@
	$(TARGET_CC) $(functional_test_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ functional_test_mod-tests_lib_functional_test.o functional_test_mod-tests_lib_test.o

mod-functional_test.o: mod-functional_test.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -c -o $@ $<

mod-functional_test.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'functional_test' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-functional_test.lst: pre-functional_test.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 functional_test/' > $@
else
def-functional_test.lst: pre-functional_test.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 functional_test/' > $@
endif

und-functional_test.lst: pre-functional_test.o
	echo 'functional_test' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

functional_test_mod-tests_lib_functional_test.o: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES)
	$(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -MD -c -o $@ $<
-include functional_test_mod-tests_lib_functional_test.d

clean-module-functional_test_mod-tests_lib_functional_test-extra.1:
	rm -f cmd-functional_test_mod-tests_lib_functional_test.lst fs-functional_test_mod-tests_lib_functional_test.lst partmap-functional_test_mod-tests_lib_functional_test.lst handler-functional_test_mod-tests_lib_functional_test.lst parttool-functional_test_mod-tests_lib_functional_test.lst video-functional_test_mod-tests_lib_functional_test.lst terminal-functional_test_mod-tests_lib_functional_test.lst

CLEAN_MODULE_TARGETS += clean-module-functional_test_mod-tests_lib_functional_test-extra.1

COMMANDFILES += cmd-functional_test_mod-tests_lib_functional_test.lst
FSFILES += fs-functional_test_mod-tests_lib_functional_test.lst
PARTTOOLFILES += parttool-functional_test_mod-tests_lib_functional_test.lst
PARTMAPFILES += partmap-functional_test_mod-tests_lib_functional_test.lst
HANDLERFILES += handler-functional_test_mod-tests_lib_functional_test.lst
TERMINALFILES += terminal-functional_test_mod-tests_lib_functional_test.lst
VIDEOFILES += video-functional_test_mod-tests_lib_functional_test.lst

cmd-functional_test_mod-tests_lib_functional_test.lst: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh functional_test > $@ || (rm -f $@; exit 1)

fs-functional_test_mod-tests_lib_functional_test.lst: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh functional_test > $@ || (rm -f $@; exit 1)

parttool-functional_test_mod-tests_lib_functional_test.lst: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh functional_test > $@ || (rm -f $@; exit 1)

partmap-functional_test_mod-tests_lib_functional_test.lst: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh functional_test > $@ || (rm -f $@; exit 1)

handler-functional_test_mod-tests_lib_functional_test.lst: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh functional_test > $@ || (rm -f $@; exit 1)

terminal-functional_test_mod-tests_lib_functional_test.lst: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh functional_test > $@ || (rm -f $@; exit 1)

video-functional_test_mod-tests_lib_functional_test.lst: tests/lib/functional_test.c $(tests/lib/functional_test.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh functional_test > $@ || (rm -f $@; exit 1)

functional_test_mod-tests_lib_test.o: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES)
	$(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -MD -c -o $@ $<
-include functional_test_mod-tests_lib_test.d

clean-module-functional_test_mod-tests_lib_test-extra.1:
	rm -f cmd-functional_test_mod-tests_lib_test.lst fs-functional_test_mod-tests_lib_test.lst partmap-functional_test_mod-tests_lib_test.lst handler-functional_test_mod-tests_lib_test.lst parttool-functional_test_mod-tests_lib_test.lst video-functional_test_mod-tests_lib_test.lst terminal-functional_test_mod-tests_lib_test.lst

CLEAN_MODULE_TARGETS += clean-module-functional_test_mod-tests_lib_test-extra.1

COMMANDFILES += cmd-functional_test_mod-tests_lib_test.lst
FSFILES += fs-functional_test_mod-tests_lib_test.lst
PARTTOOLFILES += parttool-functional_test_mod-tests_lib_test.lst
PARTMAPFILES += partmap-functional_test_mod-tests_lib_test.lst
HANDLERFILES += handler-functional_test_mod-tests_lib_test.lst
TERMINALFILES += terminal-functional_test_mod-tests_lib_test.lst
VIDEOFILES += video-functional_test_mod-tests_lib_test.lst

cmd-functional_test_mod-tests_lib_test.lst: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh functional_test > $@ || (rm -f $@; exit 1)

fs-functional_test_mod-tests_lib_test.lst: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh functional_test > $@ || (rm -f $@; exit 1)

parttool-functional_test_mod-tests_lib_test.lst: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh functional_test > $@ || (rm -f $@; exit 1)

partmap-functional_test_mod-tests_lib_test.lst: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh functional_test > $@ || (rm -f $@; exit 1)

handler-functional_test_mod-tests_lib_test.lst: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh functional_test > $@ || (rm -f $@; exit 1)

terminal-functional_test_mod-tests_lib_test.lst: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh functional_test > $@ || (rm -f $@; exit 1)

video-functional_test_mod-tests_lib_test.lst: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Itests/lib -I$(srcdir)/tests/lib $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh functional_test > $@ || (rm -f $@; exit 1)

functional_test_mod_CFLAGS  = $(COMMON_CFLAGS)
functional_test_mod_LDFLAGS = $(COMMON_LDFLAGS)

# Rules for unit tests
check_UTILITIES += example_unit_test
example_unit_test_SOURCES = tests/example_unit_test.c kern/list.c kern/misc.c tests/lib/test.c tests/lib/unit_test.c

clean-utility-example_unit_test.1:
	rm -f example_unit_test$(EXEEXT) example_unit_test-tests_example_unit_test.o example_unit_test-kern_list.o example_unit_test-kern_misc.o example_unit_test-tests_lib_test.o example_unit_test-tests_lib_unit_test.o

CLEAN_UTILITY_TARGETS += clean-utility-example_unit_test.1

mostlyclean-utility-example_unit_test.1:
	rm -f example_unit_test-tests_example_unit_test.d example_unit_test-kern_list.d example_unit_test-kern_misc.d example_unit_test-tests_lib_test.d example_unit_test-tests_lib_unit_test.d

MOSTLYCLEAN_UTILITY_TARGETS += mostlyclean-utility-example_unit_test.1

example_unit_test_OBJECTS += example_unit_test-tests_example_unit_test.o example_unit_test-kern_list.o example_unit_test-kern_misc.o example_unit_test-tests_lib_test.o example_unit_test-tests_lib_unit_test.o

example_unit_test-tests_example_unit_test.o: tests/example_unit_test.c $(tests/example_unit_test.c_DEPENDENCIES)
	$(CC) -Itests -I$(srcdir)/tests $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<
-include example_unit_test-tests_example_unit_test.d

example_unit_test-kern_list.o: kern/list.c $(kern/list.c_DEPENDENCIES)
	$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<
-include example_unit_test-kern_list.d

example_unit_test-kern_misc.o: kern/misc.c $(kern/misc.c_DEPENDENCIES)
	$(CC) -Ikern -I$(srcdir)/kern $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<
-include example_unit_test-kern_misc.d

example_unit_test-tests_lib_test.o: tests/lib/test.c $(tests/lib/test.c_DEPENDENCIES)
	$(CC) -Itests/lib -I$(srcdir)/tests/lib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<
-include example_unit_test-tests_lib_test.d

example_unit_test-tests_lib_unit_test.o: tests/lib/unit_test.c $(tests/lib/unit_test.c_DEPENDENCIES)
	$(CC) -Itests/lib -I$(srcdir)/tests/lib $(CPPFLAGS) $(CFLAGS) -DGRUB_UTIL=1 $(example_unit_test_CFLAGS) -MD -c -o $@ $<
-include example_unit_test-tests_lib_unit_test.d

example_unit_test_CFLAGS  = -Wno-format

# Rules for functional tests
pkglib_MODULES += example_functional_test.mod
example_functional_test_mod_SOURCES = tests/example_functional_test.c

clean-module-example_functional_test.mod.1:
	rm -f example_functional_test.mod mod-example_functional_test.o mod-example_functional_test.c pre-example_functional_test.o example_functional_test_mod-tests_example_functional_test.o und-example_functional_test.lst

CLEAN_MODULE_TARGETS += clean-module-example_functional_test.mod.1

clean-module-example_functional_test.mod-symbol.1:
	rm -f def-example_functional_test.lst

CLEAN_MODULE_TARGETS += clean-module-example_functional_test.mod-symbol.1
DEFSYMFILES += def-example_functional_test.lst
mostlyclean-module-example_functional_test.mod.1:
	rm -f example_functional_test_mod-tests_example_functional_test.d

MOSTLYCLEAN_MODULE_TARGETS += mostlyclean-module-example_functional_test.mod.1
UNDSYMFILES += und-example_functional_test.lst

ifneq ($(TARGET_APPLE_CC),1)
example_functional_test.mod: pre-example_functional_test.o mod-example_functional_test.o $(TARGET_OBJ2ELF)
	-rm -f $@
	$(TARGET_CC) $(example_functional_test_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ pre-example_functional_test.o mod-example_functional_test.o
	if test ! -z "$(TARGET_OBJ2ELF)"; then ./$(TARGET_OBJ2ELF) $@ || (rm -f $@; exit 1); fi
	$(STRIP) --strip-unneeded -K grub_mod_init -K grub_mod_fini -K _grub_mod_init -K _grub_mod_fini -R .note -R .comment $@
else
example_functional_test.mod: pre-example_functional_test.o mod-example_functional_test.o $(TARGET_OBJ2ELF)
	-rm -f $@
	-rm -f $@.bin
	$(TARGET_CC) $(example_functional_test_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@.bin pre-example_functional_test.o mod-example_functional_test.o
	$(OBJCONV) -f$(TARGET_MODULE_FORMAT) -nr:_grub_mod_init:grub_mod_init -nr:_grub_mod_fini:grub_mod_fini -wd1106 -nu -nd $@.bin $@
	-rm -f $@.bin
endif

pre-example_functional_test.o: $(example_functional_test_mod_DEPENDENCIES) example_functional_test_mod-tests_example_functional_test.o
	-rm -f $@
	$(TARGET_CC) $(example_functional_test_mod_LDFLAGS) $(TARGET_LDFLAGS) -Wl,-r,-d -o $@ example_functional_test_mod-tests_example_functional_test.o

mod-example_functional_test.o: mod-example_functional_test.c
	$(TARGET_CC) $(TARGET_CPPFLAGS) $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -c -o $@ $<

mod-example_functional_test.c: $(builddir)/moddep.lst $(srcdir)/genmodsrc.sh
	sh $(srcdir)/genmodsrc.sh 'example_functional_test' $< > $@ || (rm -f $@; exit 1)

ifneq ($(TARGET_APPLE_CC),1)
def-example_functional_test.lst: pre-example_functional_test.o
	$(NM) -g --defined-only -P -p $< | sed 's/^\([^ ]*\).*/\1 example_functional_test/' > $@
else
def-example_functional_test.lst: pre-example_functional_test.o
	$(NM) -g -P -p $< | grep -E '^[a-zA-Z0-9_]* [TDS]'  | sed 's/^\([^ ]*\).*/\1 example_functional_test/' > $@
endif

und-example_functional_test.lst: pre-example_functional_test.o
	echo 'example_functional_test' > $@
	$(NM) -u -P -p $< | cut -f1 -d' ' >> $@

example_functional_test_mod-tests_example_functional_test.o: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES)
	$(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -MD -c -o $@ $<
-include example_functional_test_mod-tests_example_functional_test.d

clean-module-example_functional_test_mod-tests_example_functional_test-extra.1:
	rm -f cmd-example_functional_test_mod-tests_example_functional_test.lst fs-example_functional_test_mod-tests_example_functional_test.lst partmap-example_functional_test_mod-tests_example_functional_test.lst handler-example_functional_test_mod-tests_example_functional_test.lst parttool-example_functional_test_mod-tests_example_functional_test.lst video-example_functional_test_mod-tests_example_functional_test.lst terminal-example_functional_test_mod-tests_example_functional_test.lst

CLEAN_MODULE_TARGETS += clean-module-example_functional_test_mod-tests_example_functional_test-extra.1

COMMANDFILES += cmd-example_functional_test_mod-tests_example_functional_test.lst
FSFILES += fs-example_functional_test_mod-tests_example_functional_test.lst
PARTTOOLFILES += parttool-example_functional_test_mod-tests_example_functional_test.lst
PARTMAPFILES += partmap-example_functional_test_mod-tests_example_functional_test.lst
HANDLERFILES += handler-example_functional_test_mod-tests_example_functional_test.lst
TERMINALFILES += terminal-example_functional_test_mod-tests_example_functional_test.lst
VIDEOFILES += video-example_functional_test_mod-tests_example_functional_test.lst

cmd-example_functional_test_mod-tests_example_functional_test.lst: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES) gencmdlist.sh
	set -e; 	  $(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/gencmdlist.sh example_functional_test > $@ || (rm -f $@; exit 1)

fs-example_functional_test_mod-tests_example_functional_test.lst: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES) genfslist.sh
	set -e; 	  $(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genfslist.sh example_functional_test > $@ || (rm -f $@; exit 1)

parttool-example_functional_test_mod-tests_example_functional_test.lst: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES) genparttoollist.sh
	set -e; 	  $(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genparttoollist.sh example_functional_test > $@ || (rm -f $@; exit 1)

partmap-example_functional_test_mod-tests_example_functional_test.lst: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES) genpartmaplist.sh
	set -e; 	  $(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genpartmaplist.sh example_functional_test > $@ || (rm -f $@; exit 1)

handler-example_functional_test_mod-tests_example_functional_test.lst: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES) genhandlerlist.sh
	set -e; 	  $(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genhandlerlist.sh example_functional_test > $@ || (rm -f $@; exit 1)

terminal-example_functional_test_mod-tests_example_functional_test.lst: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES) genterminallist.sh
	set -e; 	  $(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genterminallist.sh example_functional_test > $@ || (rm -f $@; exit 1)

video-example_functional_test_mod-tests_example_functional_test.lst: tests/example_functional_test.c $(tests/example_functional_test.c_DEPENDENCIES) genvideolist.sh
	set -e; 	  $(TARGET_CC) -Itests -I$(srcdir)/tests $(TARGET_CPPFLAGS)  $(TARGET_CFLAGS) $(example_functional_test_mod_CFLAGS) -E $< 	  | sh $(srcdir)/genvideolist.sh example_functional_test > $@ || (rm -f $@; exit 1)

example_functional_test_mod_CFLAGS  = -Wno-format $(COMMON_CFLAGS)
example_functional_test_mod_LDFLAGS = $(COMMON_LDFLAGS)

# Rules for scripted tests
check_SCRIPTS += example_scripted_test
example_scripted_test_SOURCES = tests/example_scripted_test.in
CLEANFILES += example_scripted_test

example_scripted_test: tests/example_scripted_test.in $(tests/example_scripted_test.in_DEPENDENCIES) config.status
	./config.status --file=-:tests/example_scripted_test.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@


check_SCRIPTS += example_grub_script_test
example_grub_script_test_SOURCES = tests/example_grub_script_test.in
CLEANFILES += example_grub_script_test

example_grub_script_test: tests/example_grub_script_test.in $(tests/example_grub_script_test.in_DEPENDENCIES) config.status
	./config.status --file=-:tests/example_grub_script_test.in | sed -e 's,@pkglib_DATA@,$(pkglib_DATA),g' > $@
	chmod +x $@



# List of tests to execute on "make check"
SCRIPTED_TESTS    = example_scripted_test
SCRIPTED_TESTS   += example_grub_script_test
UNIT_TESTS        = example_unit_test
FUNCTIONAL_TESTS  = example_functional_test.mod

# dependencies between tests and testing-tools
$(SCRIPTED_TESTS): grub-shell grub-shell-tester
$(FUNCTIONAL_TESTS): functional_test.mod

example_unit_test: $(example_unit_test_DEPENDENCIES) $(example_unit_test_OBJECTS)
	$(CC) -o $@ $(example_unit_test_OBJECTS) $(LDFLAGS) $(example_unit_test_LDFLAGS)

