#!/bin/bash -e

if test -e /boot/grub/setup_left_core_image_in_filesystem ; then
  echo -e "\n*********************** WARNING grub-setup left core.img in filesystem" >&3
fi

for i in /proc/mounts ; do
  if test -e $i ; then
    echo -e "\n*********************** BEGIN $i" >&3
    grep ^/dev/ $i >&3
    echo "*********************** END $i" >&3
  fi
done

for i in /boot/grub/{device.map,grub.cfg} ; do
  if ! test -e $i ; then
    continue
  fi
  echo -e "\n*********************** BEGIN $i" >&3
  if test -r $i ; then
    sed $i -e "s/.*password.*/### PASSWORD LINE REMOVED ###/g" >&3
  else 
    echo "$i is not readable by you. Please enter your root password."
    echo "Any password line in it gets removed."
    su root -c "sed $i -e 's/.*password.*/### PASSWORD LINE REMOVED ###/g'" >&3
  fi
  echo "*********************** END $i" >&3
done

exit 0
