.\" Copyright 2009 Felix Zielcke
.\" Lincensed under GPL3+
.TH UPDATE-GRUB "8" "April 2009"
.SH NAME
update-grub \- stub for grub-mkconfig
.SH SYNOPSIS
.B update-grub
.SH DESCRIPTION
.B update-grub
is a stub for running
.B grub-mkconfig -o /boot/grub/grub.cfg
to generate a grub2 config file.
.SH "SEE ALSO"
.BR grub-mkconfig (8)
