.\" Copyright 2009 Felix Zielcke
.\" Lincensed under GPL3+
.TH UPDATE-GRUB2 "8" "April 2009"
.SH NAME
update-grub2 \- stub for update-grub
.SH SYNOPSIS
.B update-grub2
.SH DESCRIPTION
.B update-grub2
is a stub for running
.B update-grub
which itself is a stub for running
.B grub-mkconfig -o /boot/grub/grub.cfg
to generate a grub2 config file.
.SH "SEE ALSO"
.BR update-grub (8), grub-mkconfig (8)
